### ISSUE TITLE
Client is unusable due to token changes

### ISSUE THREAD

**Issue by EddieTheCubeHead** [EddieTheCubeHead/Stagnum#242] opened 2024-04-14 19:09 UTC
No matter what core returns to the token check client doesn't redirect to login. Thus erroring requests (no token, invalid token) also don't force login. Only way to use client at the moment is to navigate to the login page manually.

Make it so erroring requests in token check force relogin.

**Comment by OttoAhlfors** [comment] 2024-04-15 06:16
Redirection works for me on master. I can look into this further but somenone needs to show me what the issue is

**Comment by EddieTheCubeHead** [comment] 2024-04-15 06:27
For me, this reproduced running with docker compose in Master. Maybe that helps?

**Comment by OttoAhlfors** [comment] 2024-04-15 07:46
Even with docker its working as it should

**Comment by EddieTheCubeHead** [comment] 2024-04-15 07:46
Then feel free to close as works as expected :+1:

**Comment by OttoAhlfors** [comment] 2024-04-15 10:14
Okay there were some changes I had not pulled and now its busted

**Comment by EddieTheCubeHead** [comment] 2024-04-15 10:15
Luckily I think the fix should be simple. If you just check return code >= 400 and reroute those to login it should work(?)

**Comment by OttoAhlfors** [comment] 2024-04-15 10:21
I am getting some cors errors

**Comment by OttoAhlfors** [comment] 2024-04-15 10:27
> Luckily I think the fix should be simple. If you just check return code >= 400 and reroute those to login it should work(?)

I dont think thats the issue the if else check that should reroute the user when code and state arent defined is workign as it should, for some reason the actual redirect fuction isnt working

**Comment by OttoAhlfors** [comment] 2024-04-15 11:04
Fix has been found, there seems to be an issue with redirect and .catch() dont know why it did not come up earlier changing redirect() to router.push() seems to work

**Closed** 2024-04-15 14:20 UTC
